# Parte 4 — Pandas en la práctica: el DataFrame
### Recorrido guiado (con datos reales) sobre `clase_fundamentos_python_CD.md`, sección 4

Un **DataFrame** es la estructura central de pandas: se puede pensar como una hoja de Excel dentro de Python (filas = registros, columnas = variables). A continuación se recorre cada subsección de la Parte 4 usando el archivo `covid_19_data.csv` de esta misma carpeta.

## 4.1 Leer datos
El archivo real se llama `covid_19_data.csv` (en las notas de clase aparece como `covid_data.csv`, solo ajusta el nombre al del archivo que tengas).

In [1]:
import pandas as pd

data = pd.read_csv("covid_19_data.csv")
data.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Hubei,Mainland China,01/22/2020 09:00,37,1,14
1,2,01/23/2020,Hubei,Mainland China,01/23/2020 09:00,66,1,26
2,3,01/24/2020,Hubei,Mainland China,01/24/2020 09:00,160,3,62
3,4,01/25/2020,Hubei,Mainland China,01/25/2020 09:00,211,3,84
4,5,01/26/2020,Hubei,Mainland China,01/26/2020 21:00,281,4,108

Otros formatos que pandas puede leer: `pd.read_excel()`, `pd.read_json()`, `pd.read_html()`, o conexión directa a bases de datos con `pd.read_sql()`.

## 4.2 Exploración inicial

In [2]:
print(data.head())      # primeros 5 registros
print(data.tail())      # últimos 5 registros
print(data.shape)       # (número de filas, número de columnas)

   SNo ObservationDate Province/State  Country/Region       Last Update  \
0    1      01/22/2020          Hubei  Mainland China  01/22/2020 09:00
1    2      01/23/2020          Hubei  Mainland China  01/23/2020 09:00
2    3      01/24/2020          Hubei  Mainland China  01/24/2020 09:00
3    4      01/25/2020          Hubei  Mainland China  01/25/2020 09:00
4    5      01/26/2020          Hubei  Mainland China  01/26/2020 21:00

   Confirmed  Deaths  Recovered
0         37       1         14
1         66       1         26
2        160       3         62
3        211       3         84
4        281       4        108
     SNo ObservationDate Province/State Country/Region       Last Update  \
895  896      04/16/2020            NaN         France  04/16/2020 17:00
896  897      04/17/2020            NaN         France  04/17/2020 17:00
897  898      04/18/2020            NaN         France  04/18/2020 17:00
898  899      04/19/2020            NaN         France  04/19/2020 21:00
899  900      04/20/2020            NaN         France  04/20/2020 09:00

     Confirmed  Deaths  Recovered
895       4306      94       1853
896       4342      94       1864
897       4422      94       1901
898       4477      97       1930
899       4529      97       1958
(900, 8)

In [3]:
data.info()      # tipo de dato por columna, nulos, memoria usada

<class 'pandas.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SNo              900 non-null    int64
 1   ObservationDate  900 non-null    str
 2   Province/State   720 non-null    str
 3   Country/Region   900 non-null    str
 4   Last Update      900 non-null    str
 5   Confirmed        900 non-null    int64
 6   Deaths           900 non-null    int64
 7   Recovered        900 non-null    int64
dtypes: int64(4), str(4)
memory usage: 56.4 KB

In [4]:
data.describe()  # estadísticas básicas (media, min, max, percentiles...)

              SNo    Confirmed      Deaths    Recovered
count  900.000000   900.000000  900.000000   900.000000
mean   450.500000  1536.577778   32.541111   659.367778
std    259.951919  1156.808432   25.504552   501.385506
min      1.000000    10.000000    0.000000     5.000000
25%    225.750000   597.750000   13.000000   247.750000
50%    450.500000  1220.000000   26.000000   526.000000
75%    675.250000  2208.500000   46.250000   953.750000
max    900.000000  4529.000000  107.000000  1958.000000

## 4.3 Tipos de dato y fechas
Por default, pandas lee las columnas de fecha como texto (`object`). Nota que arriba, en `data.info()`, `ObservationDate` y `Last Update` aparecen como `object`, no como fecha. Para poder ordenar/filtrar por fecha, hay que indicarle explícitamente a `read_csv` cuáles columnas son fechas:

In [5]:
data = pd.read_csv("covid_19_data.csv", parse_dates=["ObservationDate", "Last Update"])
data.info()   # ahora esas columnas aparecen como datetime64

<class 'pandas.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SNo              900 non-null    int64
 1   ObservationDate  900 non-null    datetime64[us]
 2   Province/State   720 non-null    str
 3   Country/Region   900 non-null    str
 4   Last Update      900 non-null    datetime64[us]
 5   Confirmed        900 non-null    int64
 6   Deaths           900 non-null    int64
 7   Recovered        900 non-null    int64
dtypes: datetime64[us](2), int64(4), str(2)
memory usage: 56.4 KB

**Por qué importa:** solo se pueden hacer operaciones temporales (ordenar cronológicamente, filtrar por rango de fechas, graficar series de tiempo) si el tipo de dato es `datetime`, no texto.

## 4.4 Selección de columnas y valores únicos

In [6]:
data["Country/Region"]              # selecciona una columna (Serie de pandas)

0      Mainland China
1      Mainland China
2      Mainland China
3      Mainland China
4      Mainland China
            ...
895            France
896            France
897            France
898            France
899            France
Name: Country/Region, Length: 900, dtype: str

In [7]:
data["Country/Region"].unique()     # lista de valores distintos en esa columna

<StringArray>
['Mainland China', 'US', 'Australia', 'Mexico', 'France']
Length: 5, dtype: str

Útil para: explorar categorías disponibles, y verificar que un filtro funcionó correctamente.

## 4.5 Filtrado de filas

In [8]:
china = data[data["Country/Region"] == "Mainland China"]
mexico = data[data["Country/Region"] == "Mexico"]

print(china["Country/Region"].unique())
print(mexico["Country/Region"].unique())

<StringArray>
['Mainland China']
Length: 1, dtype: str
<StringArray>
['Mexico']
Length: 1, dtype: str

**Buena práctica de exploración:** después de filtrar, verificar con `.unique()` que solo quedó lo esperado, y revisar con `.head()`/`.tail()` el resultado.

In [9]:
print(china.head())
print(china.tail())

print("Provincias/estados en China:", china["Province/State"].unique())
print("Provincias/estados en México:", mexico["Province/State"].unique())

   SNo ObservationDate Province/State  Country/Region         Last Update  \
0    1      2020-01-22          Hubei  Mainland China 2020-01-22 09:00:00
1    2      2020-01-23          Hubei  Mainland China 2020-01-23 09:00:00
2    3      2020-01-24          Hubei  Mainland China 2020-01-24 09:00:00
3    4      2020-01-25          Hubei  Mainland China 2020-01-25 09:00:00
4    5      2020-01-26          Hubei  Mainland China 2020-01-26 21:00:00

   Confirmed  Deaths  Recovered
0         37       1         14
1         66       1         26
2        160       3         62
3        211       3         84
4        281       4        108
     SNo ObservationDate Province/State  Country/Region         Last Update  \
265  266      2020-04-16       Zhejiang  Mainland China 2020-04-16 21:00:00
266  267      2020-04-17       Zhejiang  Mainland China 2020-04-17 17:00:00
267  268      2020-04-18       Zhejiang  Mainland China 2020-04-18 09:00:00
268  269      2020-04-19       Zhejiang  Mainland China 2020-04-19 21:00:00
269  270      2020-04-20       Zhejiang  Mainland China 2020-04-20 21:00:00

     Confirmed  Deaths  Recovered
265        969      17        397
266        982      17        401
267        989      17        405
268       1006      17        413
269       1018      18        416
Provincias/estados en China: <StringArray>
['Hubei', 'Guangdong', 'Zhejiang']
Length: 3, dtype: str
Provincias/estados en México: <StringArray>
[nan]
Length: 1, dtype: str

Aquí se ve la diferencia de granularidad mencionada en las notas: China reporta por provincia/estado, mientras que México solo tiene un registro por país (sin desagregar). Esto importa antes de decidir a qué nivel se puede hacer el análisis.

## 4.6 Agrupar y agregar (`groupby`)

In [10]:
data.groupby("Country/Region")["Confirmed"].max()

Country/Region
Australia         3835
France            4529
Mainland China    4259
Mexico            4365
US                4171
Name: Confirmed, dtype: int64

Esto responde: *"para cada país, ¿cuál fue el número máximo de confirmados registrado en un solo día?"*. Otras funciones de agregación: `.sum()`, `.min()`, `.mean()`, `.count()`.

`groupby` cambia la estructura de índices del resultado (el país queda como índice, no como columna); `.reset_index()` regresa el resultado a un DataFrame "plano", fácil de seguir usando con la notación habitual (`casos_pais["Country/Region"]`, por ejemplo).

In [11]:
casos_pais = data.groupby("Country/Region")["Confirmed"].max().reset_index()
casos_pais

   Country/Region  Confirmed
0       Australia       3835
1          France       4529
2  Mainland China       4259
3          Mexico       4365
4              US       4171

## 4.7 Ordenar (`sort_values`)

In [12]:
casos_pais.sort_values("Confirmed", ascending=False)   # de mayor a menor

   Country/Region  Confirmed
1          France       4529
3          Mexico       4365
2  Mainland China       4259
4              US       4171
0       Australia       3835

In [13]:
casos_pais.sort_values("Confirmed", ascending=True)    # de menor a mayor (default)

   Country/Region  Confirmed
0       Australia       3835
4              US       4171
2  Mainland China       4259
3          Mexico       4365
1          France       4529

## 4.8 Tablas dinámicas (`pivot_table`)

**Nota sobre esta versión de pandas:** el ejemplo de las notas de clase usa `aggfunc="sum"` sin indicar `values`, lo que hace que pandas intente sumar *todas* las columnas numéricas y de fecha del DataFrame. En versiones recientes de pandas esto produce un error (`TypeError: datetime64 type does not support operation 'sum'`), porque no tiene sentido "sumar" fechas. La solución es indicar explícitamente qué columnas se quieren agregar con el parámetro `values`.

In [14]:
# Código literal de las notas de clase -> falla en esta versión de pandas
try:
    resumen = data.pivot_table(
        index=["Country/Region", "Province/State"],
        aggfunc="sum"
    )
except TypeError as e:
    print("Error esperado:", e)

Error esperado: datetime64 type does not support operation 'sum'

In [15]:
# Versión corregida: se indican explícitamente las columnas numéricas a sumar
resumen = data.pivot_table(
    index=["Country/Region", "Province/State"],
    values=["Confirmed", "Deaths", "Recovered"],
    aggfunc="sum"
)
resumen

                                Confirmed  Deaths  Recovered
Country/Region Province/State
Australia      New South Wales     175525    3343      79480
               Victoria             58396    1480      24285
Mainland China Guangdong           104174    2400      45295
               Hubei               186244    4621      78049
               Zhejiang             46471     857      19162
US             California          197911    4505      82349
               New York             92000    1990      40466
               Texas               102721    2317      43079

El **índice** (index) es la estructura que pandas usa para localizar información eficientemente (no hay que recorrer fila por fila). `pivot_table` permite reorganizar y agregar datos según distintos niveles (país, provincia, fecha, etc.) según lo que necesite el análisis.

Para filtrar dentro de un índice de varios niveles (MultiIndex), se usa `.loc`:

In [19]:
resumen.loc["Mainland China"]

                Confirmed  Deaths  Recovered
Province/State
Guangdong          104174    2400      45295
Hubei              186244    4621      78049
Zhejiang            46471     857      19162

**Otro detalle importante encontrado con datos reales:** las notas de clase usan `resumen.loc[\"Mexico\"]` como ejemplo, pero con este dataset eso lanza `KeyError: 'Mexico'`. La razón no es un error de pandas, sino de los datos: `pivot_table` descarta las filas cuyo valor en una columna del índice es `NaN`, y México (igual que Francia) no reporta `Province/State` (todas sus filas tienen `NaN` en esa columna), así que desaparece por completo del índice de `resumen`. Es justo el punto que menciona la sección 4.5: algunos países reportan por provincia/estado y otros no, y eso cambia a qué nivel se puede analizar cada uno. Se puede comprobar así:

In [18]:
print(data[data["Country/Region"] == "Mexico"]["Province/State"].unique())
print("Mexico" in resumen.index.get_level_values(0))

<StringArray>
[nan]
Length: 1, dtype: str
False

---
### Resumen de la Parte 4
- `pd.read_csv(..., parse_dates=[...])` para que las fechas queden como `datetime`, no texto.
- `.head()`, `.tail()`, `.shape`, `.info()`, `.describe()` para explorar un DataFrame antes de transformarlo.
- `data["columna"].unique()` para ver categorías disponibles y verificar filtros.
- `data[data["columna"] == valor]` para filtrar filas.
- `groupby(...).agg().reset_index()` para agrupar y volver a un DataFrame plano.
- `sort_values(...)` para ordenar.
- `pivot_table(..., values=[...], aggfunc=...)` para tablas dinámicas — siempre indicando `values` explícitamente cuando el DataFrame tiene columnas de fecha, para evitar el error de tipo visto arriba.